#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
#if (( $+commands[fortune] )); then
#    if (( $+commands[cowsay] )); then
#        if (( $+commands[lolcat] )); then
#          fortune -s | cowsay | lolcat
#          print
#        else
#          fortune -s | cowsay
#          print
#      fi
#  else
#      fortune -s
#      print
#    fi
#fi

